### ISSUE TITLE
Current version of website and server 5e 350

### ISSUE THREAD

**Issue by Smarthome-Creator** [davidm-glitch/home-assistant-eheim-digital#1]
Website: 1.01.3
Server: 1.00.8

**Comment by davidm-glitch** [comment]
So its the same as on my 700. Can you also check the websocket communication?
You can check the wiki to see if its the same as mine

**Comment by davidm-glitch** [comment]
Its easy, open the ip of your filter in your browser and open the developer tools (F12), go to network tab. You can select "WS" to filter the results. After that you have to refresh the page again (and maybe remove the "/#/top" from the url. If it loaded you should see one result in the list and if you click on it you can see the communication.

**Comment by Smarthome-Creator** [comment]
I can see a lot of informations. I hope this is what you mean:
<img width="1466" alt="image" src="https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/61153058/75668456-9803-4ec9-ae70-25201daed18a">

**Comment by davidm-glitch** [comment]
yes exactly! Can you send me the content of one message with title "FILTER_DATA".

I hope I can update the code and instructions on how to install it in the next days!

**Comment by Smarthome-Creator** [comment]
Hello, hopefully here is the right information for you:

title: "FILTER_DATA", from: "X:X:X:X:X:X", minFreq: 3500, maxFreq: 6700, maxFreqRglOff: 7200,…}
actualTime
: 
2835
dfs
: 
666
dfsFaktor
: 
1517
end_time_night_mode
: 
420
filterActive
: 
1
freq
: 
4400
freqSoll
: 
4400
from
: 
"X:X:X:X:X:X"
isEheim
: 
0
maxFreq
: 
6700
maxFreqRglOff
: 
7200
minFreq
: 
3500
nm_dfs_soll_day
: 
1
nm_dfs_soll_night
: 
0
pm_dfs_soll_high
: 
11
pm_dfs_soll_low
: 
1
pm_time_high
: 
10
pm_time_low
: 
10
pumpMode
: 
1
rotSpeed
: 
26
runTime
: 
1067895
serviceHour
: 
4320
sollStep
: 
0
start_time_night_mode
: 
1200
title
: 
"FILTER_DATA"
to
: 
"USER"
turnOffTime
: 
0
turnTimeFeeding
: 
0
version
: 
74

I will test your integration tomorrow.

**Comment by davidm-glitch** [comment]
Thats exactly the information I needed, so it seems that all filter sizes are the same in terms of software. That's good to know!

The script will for now not be like a normal integration. At first it will be a script that can be run out of Home Assistant. I will update the readme as soon as it is working and ready to use!

**Comment by davidm-glitch** [comment]
@Smarthome-Creator 
could you also check on the "{title: "USRDTA", .... " message for me?
what does your filter say there?
