### ISSUE TITLE
Support for LEDcontrol+e V1

### ISSUE THREAD

**Issue by TheBoringGuy1908** [davidm-glitch/home-assistant-eheim-digital#12]
Hey there and thanks a lot for making this integration!
As requested I would be happy to help with the LEDcontrol+e v1 integration, since I own that device.
Please let me know how I can help :)

**Comment by davidm-glitch** [comment]
Hey, thanks for your message. 

Did you try if the integration already works for you? I don't know how different v1 and v2 are?

**Comment by TheBoringGuy1908** [comment]
Hey, the integration itself works, but the LEDcontrol device is not recognized.
I have a filter, a heater and the PHcontrol device in addition to the LEDcontrol, all of which are recognized by the integration (even though they often disconnect or don't show certain values.. - I assume that's due to the early state of the integration)

All devices are connected to PHcontrol.
I tried taking a look at the web socket messages through the Chrome Debug Tools but could only find parts of the LEDcontrol values.

**Comment by davidm-glitch** [comment]
You can check this discussion for the information how to get the websocket data.

https://github.com/davidm-glitch/home-assistant-eheim-digital/discussions/5

Most important is the device version number for us. Maybe you can post the data then we can try to include V1 as well ;)

**Comment by davidm-glitch** [comment]
You can check this discussion for the information how to get the websocket data.

https://github.com/davidm-glitch/home-assistant-eheim-digital/discussions/5#discussioncomment-6754889

Most important is the device version number for us. Maybe you can post the data then we can try to include V1 as well ;)

**Comment by TheBoringGuy1908** [comment]
Interestingly, I restarted Homeassistant yesterday and the light controller showed up. All 4 values for the light channels are working, so as it seems that there is nothing to do. Sorry for the confusion.

**Comment by davidm-glitch** [comment]
Ah, very nice! Sometimes it helps to reload the integration again. Connection is a bit buggy.

Please report how stable this works now. I have the problem that my led control stops responding after a few days and I have to reboot it.
