### ISSUE TITLE
Converting into core Home Assistant component?

### ISSUE THREAD

**Issue by autinerd** [davidm-glitch/home-assistant-eheim-digital#13]
Hi,

I just stumbled on this project. A few months ago I started working on a Eheim Digital integration myself and continued working on it yesterday.

I currently have a very rudimentary module for the communication: (Not published yet on PyPI) https://github.com/autinerd/eheimdigital

And I also created an integration in Home Assistant Core: https://github.com/autinerd/core/tree/add-eheimdigital/homeassistant/components/eheimdigital
(It's also still rough, but my thermocontrol+ is found and can be controlled.)

I unfortunately only have a single EHEIM.digital device currently, so I can't really test with multiple devices.

Maybe we can work together to get the integration combined and submitted to a core Home Assistant integration?

Greetings,
Sid

**Comment by davidm-glitch** [comment]
Hey Sid!

Nice to see that there are more crazy people out there who want to get this to work ;)

It would be nice to work together to make this a core component, but for this there is a lot of work to do.

Did you try this integration? For me it works quite well, but there are still a lot of values missing and we didnt even start with sending commands. 

@jkhalil is doing most of the coding stuff as my python skills are very basic. I do all the administrative stuff and update the Wiki. Did you check the wiki yet?

BR, David

**Comment by jkhalil** [comment]
@autinerd Let us what you need from us.  I can help with what ever yo uneed.

**Comment by jkhalil** [comment]
Hey Sid.

I was starting to do a refactor on this custom integration and I thought it would just be better to merge the work between the two of our code bases. I have done quite a bit that could be an easy copy paste to create a core module.

The current integration could greatly benefit from a eheimdigital_aio as you started to create for the communication.

Let me know if you are still wanting to colab, we are on a discord server where people would like to contribute to the project too.

**Comment by davidm-glitch** [comment]
long time no update here, closing the issue.
