### ISSUE TITLE
Bleibt es nur bei den Sensoren?

### ISSUE THREAD

**Issue by Smarthome-Creator** [davidm-glitch/home-assistant-eheim-digital#15]
Hallo @davidm-glitch ,

ich habe eine Frage. Mit deinem Script war es damals ja möglich den Filter ein und aus zu schalten und das Pumpenverhalten zu ändern.

Ist geplant das wieder zu integrieren oder ist das aus technischen Gründen nicht möglich? Die Futterpause vom Filter ist halt schon gut und das über eine Schaltbare Steckdose zu machen ist nicht sehr sinnvoll, da das immer die Sensoren zurücksetzt.

Was noch eine gute Sache wäre, wäre die Geräte per DNS Namen integrieren zu können und nicht über die IP. IP's ändern sich. ;-)

**Comment by davidm-glitch** [comment]
Hey, also die Funktionen zum steuern sind noch in Planung ja. Allerdings sind sowohl ich als auch @jkhalil mit Nachwuchs sehr eingespannt ;)

Hast du es mit dem DNS Namen mal ausprobiert? Wüsste nicht wieso es nicht klappen sollte. Ansonsten kann man den Geräten in seinem Router eine feste IP zuordnen, dann ändert die sich nicht mehr :)

**Comment by Smarthome-Creator** [comment]
@davidm-glitch, mit dem DNS Namen hast du vollkommen recht. Manchmal sieht man den Wald vor lauter Bäumen nicht. Man kann nicht IP entfernen und gegen Namen tauschen wenn man die Integration nicht neu startet. ;-)

Schön zu hören das ihr da dran seid. Viel Spaß mit dem Nachwuchs.
