### ISSUE TITLE
ph Setpoint of phcontrol+e is not displayed correctly at night when operating in bio mode

### ISSUE THREAD

**Issue by MrSeccubus** [davidm-glitch/home-assistant-eheim-digital#24]
On the device:
<img width="1193" alt="Screenshot 2024-11-26 at 23 03 06" src="https://github.com/user-attachments/assets/55eaff61-7904-4491-b320-690b4f32f14d">

Screenshot was taken at ~ 23:00 so setpoint was set to night: 7.3

In Home Assistant
<img width="596" alt="Screenshot 2024-11-26 at 23 04 17" src="https://github.com/user-attachments/assets/4774514c-45de-4044-bb5b-8e418f956e5c">

Setpoint shows as the day setpoint.

**Comment by MrSeccubus** [comment]
It looks like you are actually getting the wrong setpoint back via the websocket.

<img width="918" alt="Screenshot 2024-11-26 at 23 11 22" src="https://github.com/user-attachments/assets/e5bed233-3f59-4eb2-91aa-02812a722dc5">

**Comment by davidm-glitch** [comment]
Do you see any value that fits the night kH setpoint?

**Comment by MrSeccubus** [comment]
The line:
```
"schedule" : [[ 450, 74], [1080, 78]]
```
Seems to have the right times ( `450 / 60 = 7.5 = 7:30`, `1080 / 60 = 18 = 18:00`) but not the right setpoints. 

I'm not at home right now, but maybe there is a `bio` property too we need to find out the `mode` first (`setpoint`, `bio` or `schedule`)?

**Comment by MrSeccubus** [comment]
So, I figured it out.

```
if data["mode"] == 0 : # Simple setpoint
  value_fn=lambda data: round((int(data["sollPH"]) / 10), 1)
elif data["mode"] == 1: # Bio mode
  now = datetime.now().hour
  currentMin = now.hour * 60 + now.minute
  if data["expert"] == 0: # Not exper mode, use dayStartT etc
    if now < data["dayStartT] or now >= ["nightStartT"] :
      value_fn=lambda data: round((int(data["sollPH"])-(int(data["nReduce"]) / 10), 1)
  elif data["expert"] == 1: # Expert mode, use schedule
    for index, schedule = enumerate(data["schedule"]):
      if index < len(data["schedule"]) - 1:
        if currentMin >= schedule[0] and  currentMin < data["schedule"][index+1][0]:
          value_fn=lambda data: round((int(data["schedule"][index][1] / 10), 1)
      else:
        if currentMin >= schedule[0] or  currentMin < data["schedule"][0][0]:
          value_fn=lambda data: round((int(data["schedule"][index][1] / 10), 1)
else:
  pass
  # There is a "Smart Mode", but since I only have one device, I cannot pair it with a LED controller to test this
```

**Comment by MrSeccubus** [comment]
`mode` is either 0, 1 or 2(?):
0: single setpoint, sollPh is the current PH setpunt
1: Bio mode, the controller is on a schedule
2: Smart mode (value is a guess since I cannot test it)

`export` either 0 or 1, indicates if a simple day/night schedule is in place or a more advanced schedule
0: day/night schedule, before `dayStartT` or after `nightStartT` the ph setpointvalue is reduced by `nReduce`
1: schedule in the `schedule` parameter is used.
