### ISSUE TITLE
‘ClientConnection’ object has no attribute ‘closed’

### ISSUE THREAD

**Issue by davidm-glitch** [davidm-glitch/home-assistant-eheim-digital#26]
@jkhalil can you take a quick look at it?

**Comment by crusader85** [comment]
Same problem here

**Comment by Sanderjanson** [comment]
Same here, home assistant core 2024.12.2 kills the integration!
Went back to 2024.11.1 and it works again!

is there a workaround?

**Comment by joshua-dessol** [comment]
Update this file /homeassistant/custom_components/eheim_digital/manifest.json

from:

`"requirements": ["websockets"]`

to:

`"requirements": ["websockets==13.0"]`

then it should work again.

**Comment by Sanderjanson** [comment]
> Update this file /homeassistant/custom_components/eheim_digital/manifest.json
> 
> from:
> 
> `"requirements": ["websockets"]`
> 
> to:
> 
> `"requirements": ["websockets==13.0"]`
> 
> then it should work again.

Thanks! It didn’t for me, but 13.1 works, I completely don’t know why, but is works now!


Or do I get somewhere else in trouble with this?

**Comment by davidm-glitch** [comment]
Thanks for your help!

I already tried it but it didn't work with 13.0 for me so I reverted the change. 13.1 seems to work fine!

New release is published via hacs. 🎉
